# -*- coding: utf-8 -*-
"""Copy of ProjectDatagov.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1itzM7NDoht7z6Rn0Qf39y_idI5E2FHe4
"""

!pip install panda
!pip install openpyxl==3.1.2
!pip install numpy

import pandas as pd
credit_card = pd.read_csv('creditcard.csv')
credit_card.head()

import pandas as pd
import numpy as np
credit_card = pd.read_csv('creditcard.csv')

credit_card.sample(5)

duplicate = credit_card[credit_card.duplicated()]
duplicate

credit_card.drop_duplicates()

credit_card.drop_duplicates(inplace=True)

missing_values_count = credit_card.isnull().sum()
missing_values_count[:]

missing_values_count =credit_card.isnull().sum()
print("Missing Values:\n", missing_values_count)

import numpy as np

total_cells = np.prod(credit_card.shape)
total_missing = missing_values_count.sum()

# percent of data that is missing
(total_missing/total_cells) * 100

credit_card.dropna()

subset_card = credit_card.loc[:, 'V1':'V28'].head()
subset_card

subset_card.fillna(0)

print(credit_card.columns)

import matplotlib.pyplot as plt
import seaborn as sns

import pandas as pd
import matplotlib.pyplot as plt
credit_card = pd.read_csv('creditcard.csv')
credit_card.columns = credit_card.columns.str.lower()
numerical_columns = ['v1', 'v2', 'v3', 'v4', 'v5', 'v6', 'v7', 'v8', 'v9', 'v10', 'v11', 'v12',
                     'v13', 'v14', 'v15', 'v16', 'v17', 'v18', 'v19', 'v20', 'v21', 'v22', 'v23',
                     'v24', 'v25', 'v26', 'v27', 'v28']
existing_columns = [col for col in numerical_columns if col in credit_card.columns]
if existing_columns:
    credit_card[existing_columns].plot(kind='box', subplots=True, layout=(7, 4), figsize=(15, 20), fontsize=8)
    plt.tight_layout()
    plt.show()
else:
    print("No matching columns found for the boxplot.")

!pip install pandera
import pandas as pd
import pandera as pa
from pandera import Column, Check, DataFrameSchema
df = pd.read_csv('creditcard.csv')
schema = pa.DataFrameSchema(
    {
        "Time": Column(float, Check.ge(0)),
        "V1": Column(float),
        "V2": Column(float),
        "V3": Column(float),
        "V4": Column(float),
        "V5": Column(float),
        "V6": Column(float),
        "V7": Column(float),
        "V8": Column(float),
        "V9": Column(float),
        "V10": Column(float),
        "V11": Column(float),
        "V12": Column(float),
        "V13": Column(float),
        "V14": Column(float),
        "V15": Column(float),
        "V16": Column(float),
        "V17": Column(float),
        "V18": Column(float),
        "V19": Column(float),
        "V20": Column(float),
        "V21": Column(float),
        "V22": Column(float),
        "V23": Column(float),
        "V24": Column(float),
        "V25": Column(float),
        "V26": Column(float),
        "V27": Column(float),
        "V28": Column(float),
        "Amount": Column(float, Check.ge(0)),
        "Class": Column(int, Check.isin([0, 1])),
    }
)

try:
    schema.validate(df, lazy=True)
    print("Data is valid!")
except pa.errors.SchemaErrors as exc:
    print("Schema validation errors found:")
    failure_cases_df = exc.failure_cases
    print(failure_cases_df)

import pandas as pd
credit_card = pd.read_csv('creditcard.csv')
numerical_columns = credit_card.select_dtypes(include=['number']).columns
Q1 = credit_card[numerical_columns].quantile(0.25)
Q3 = credit_card[numerical_columns].quantile(0.75)
IQR = Q3 - Q1


print('IQR Scores of columns:\n', IQR)

credit_card

!pip install pandera
import pandera as pa
import pandas as pd
from pandera import Column, DataFrameSchema, Check, Index

!pip install pandera[io]
import pandas as pd
import pandera as pa
credit_card = pd.read_csv('creditcard.csv')
inferred_schema = pa.infer_schema(credit_card).to_script()
print(inferred_schema)

!pip install cerberus
import pandas as pd
from cerberus import Validator
df = pd.read_csv("creditcard.csv")
schema = {
    'Time': {'type': 'number', 'min': 0},
    'Amount': {'type': 'number', 'min': 0},
    'Class': {'type': 'integer', 'allowed': [0, 1]}
}
for i in range(1, 29):
    schema[f'V{i}'] = {'type': 'number'}
v = Validator(schema)
for idx, row in df.head(10).iterrows():
    row = row.to_dict()
    row['Class'] = int(row['Class'])
    if v.validate(row):
        print(f"Row {idx}:  Valid")
    else:
        print(f"Row {idx}:  Invalid")
        print(f"Errors: {v.errors}")