# -*- coding: utf-8 -*-
"""Copy of profiling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pM-ppENWQEiG9T8DDWqpPvn9VwuXTQrA
"""

!pip install sweetviz
!pip install pandas
!pip install dataprofiler
!pip install ydata_profiling

import sweetviz as sv
import pandas as pd

df = pd.read_csv('/content/creditcard.csv')
report = sv.analyze(df)
report.show_html('sweetviz_report.html')

from ydata_profiling import ProfileReport
import pandas as pd

df = pd.read_csv('/content/creditcard.csv')
profile = ProfileReport(df, title="Data Profiling Report")
profile.to_file("report.html")

import json
from dataprofiler import Data, Profiler

data = Data('/content/creditcard.csv')
profile = Profiler(data)

report  = profile.report(report_options={"output_format":"pretty"})


print(json.dumps(report, indent=4))