# -*- coding: utf-8 -*-
"""Copy of  PrivacyandSecurity(!).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XSKsDxCK6uaCYMBnSpoYrV49dkYymxMg
"""

import pandas as pd
from cryptography.fernet import Fernet
 #Load the dataset
df = pd.read_csv('creditcard.csv')
 #Generate an encryption key
key = Fernet.generate_key()
cipher_suite = Fernet(key)
 #Encrypt the Amount
encrypted_creditcard = [cipher_suite.encrypt(str(h).encode()).decode() for h in df['Amount']]
df['encrypted_creditcard'] = encrypted_creditcard
 #Save the pseudonymized dataset
df.to_csv('pseudonymized_data.csv', index=False)

import pandas as pd
import random
# Load dataset
df = pd.read_csv('creditcard.csv')

# Caesar Cipher for numbers (digit-wise)
def caesar_cipher_number(num):
    shift = random.randint(1,9)
    encrypted = ''
    for digit in str(int(num)):  # Convert to int to remove decimals
        if digit.isdigit():  # Ensure it's a digit
            encrypted += str((int(digit) + shift) % 10)  # Shift the digit and wrap around
        else:
            encrypted += digit  # If it's not a digit (e.g., decimal point), leave as is
    return encrypted , shift

# Apply Caesar Cipher to the 'Amount' column
df['caesar_encrypted_amount'], df['shift_used']= zip(*df['Amount'].apply(caesar_cipher_number))

# Save the encrypted dataset
df.to_csv('caesar_encrypted_creditcard.csv', index=False)

print("Caesar cipher encryption complete. Encrypted file saved as 'caesar_encrypted_creditcard.csv'")
print("\nFirst 5 encrypted values with their shifts:")
print(df[['Amount', 'caesar_encrypted_amount', 'shift_used']].head())

from collections import Counter

# Load the encrypted dataset
df = pd.read_csv('caesar_encrypted_creditcard.csv')

# Step 1: Collect all digits from the encrypted 'Amount' column
all_encrypted_digits = ''.join(df['caesar_encrypted_amount'].dropna().astype(str).str.cat())

# Step 2: Count the frequency of each digit (0–9)
digit_freq = Counter(all_encrypted_digits)

print("Encrypted Digit Frequencies:")
for digit, freq in digit_freq.items():
    print(f"Digit: {digit}, Frequency: {freq}")

# Step 3: Assuming and comparing
def decrypt_digit_caesar(text, shift):
    decrypted = ''
    for digit in str(text):
        if digit.isdigit():
            decrypted += str((int(digit) - shift) % 10)
        else:
            decrypted += digit
    return decrypted

# Step 4: Try each possible shift and preview the result
print("\nTrying all Caesar shifts to guess the original data (previewing first 5 values each):")
for shift in range(1, 10):
    df[f'decrypted_amount_shift_{shift}'] = df['caesar_encrypted_amount'].apply(lambda x: decrypt_digit_caesar(x, shift))
    print(f"\nShift {shift}:")
    print(df[f'decrypted_amount_shift_{shift}'].head())

import hashlib
import pandas as pd

# Load the dataset
df = pd.read_csv('creditcard.csv')

# Hash the 'Amount' column (replace with your desired numerical column) using SHA-256
df['hashed_creditcard'] = df['Amount'].apply(lambda x: hashlib.sha256(str(x).encode()).hexdigest())

# Save the pseudonymized dataset
df.to_csv('pseudonymized1_data.csv', index=False)

import pandas as pd

# Load the credit card fraud detection dataset (replace 'creditcard.csv' with the actual file name)
df = pd.read_csv('creditcard.csv')

# Generalize the 'Time' column (example: create time periods)
df['time_period'] = pd.cut(df['Time'], bins=[0, 10000, 20000, 30000, float('inf')],
                           labels=['00:00-06:00', '06:00-12:00', '12:00-18:00', '18:00-24:00'])

# Example: Generalize the 'Amount' column into ranges
df['amount_range'] = pd.cut(df['Amount'], bins=[0, 50, 100, 500, 1000, float('inf')],
                            labels=['<50', '50-100', '100-500', '500-1000', '1000+'])

# Drop the original 'Time' and 'Amount' columns to anonymize the data
df.drop(['Time', 'Amount'], axis=1, inplace=True)

# Save the anonymized dataset
df.to_csv('anonymized_creditcard_data.csv', index=False)

# Display the first few rows to check the result
print(df.head())

import pandas as pd

# Load the dataset
df = pd.read_csv('creditcard.csv')

# Remove the columns that might be sensitive (for this example, we'll drop 'Time' and 'Amount')
# These might be considered sensitive depending on the context; however, you can choose other columns to drop as needed.
df.drop(['Time', 'Amount'], axis=1, inplace=True)

# Save the anonymized dataset
df.to_csv('anonymized_creditcard_data.csv', index=False)

print("Suppression applied. Anonymized dataset saved as 'anonymized_creditcard_data.csv'")

import pandas as pd
import numpy as np


df = pd.read_csv('creditcard.csv')

# Add random noise to the 'Amount' column
df['Amount'] = df['Amount'] + np.random.normal(0, 1000, len(df))


df.to_csv('anonymized_creditcard_data.csv', index=False)

print("Randomization applied. Anonymized dataset saved as 'anonymized_creditcard_data.csv'")

!pip install faker
import pandas as pd
from faker import Faker

# Load the dataset
df = pd.read_csv('creditcard.csv')

# Initialize the Faker object
fake = Faker()

# Mask the 'Time' column with fake data (for example, we can generate random timestamps)
df['Time'] = [fake.date_this_century() for _ in range(len(df))]

#mask amount column w keda
df['Amount'] = [fake.random_number(digits=5) for _ in range(len(df))]

# Save the anonymized dataset
df.to_csv('anonymized_creditcard_data.csv', index=False)

print("Data Masking applied. Anonymized dataset saved as 'anonymized_creditcard_data.csv'")

"""RBAC Access control

"""

import pandas as pd

#RBAC data
roles = ['jr_editor', 'editor', 'it']
permissions = ['read', 'create', 'update', 'delete']

# Create a DataFrame
rbac_df = pd.DataFrame(columns=['Role'] + permissions)
rbac_df['Role'] = roles
rbac_df.set_index('Role', inplace=True)

# Fill in permission
rbac_df.loc['jr_editor', 'read'] = 1
rbac_df.loc['editor', 'create'] = 1
rbac_df.loc['it', ['create', 'read', 'update', 'delete']] = 1


print("Initial RBAC DataFrame:")
print(rbac_df)

# roles bt3tna
user_roles = {
    "Omar": "editor",
    "Nour": "jr_editor",
    "Abdullah": "it"
}

# Function to check permission
def has_permission(user_role, required_permission):
    """Checks if a user has the required permission using the rbac_df."""
    try:
        permission_value = rbac_df.loc[user_role, required_permission]
        return permission_value == 1  # Assuming 1 means permission granted
    except KeyError:
        return False  # Role or permission not found in DataFrame

# Example checks for each user
for user, role in user_roles.items():
    required_permission = "read"  # Change this to check other permissions (e.g., "create")

    if has_permission(role, required_permission):
        print(f"User '{user}' with role '{role}' has permission to '{required_permission}'.")
    else:
        print(f"User '{user}' with role '{role}' does not have permission to '{required_permission}'.")

# Print the final RBAC DataFrame
print("\nFinal RBAC DataFrame:")
print(rbac_df)

"""# GDPR"""

!pip install pandas

import pandas as pd
import hashlib

# Load our dataset
df = pd.read_csv('creditcard.csv')

# Display the first few rows
df.head()

# Function to hash sensitive columns
def hash_column(data):
    return data.apply(lambda x: hashlib.sha256(str(x).encode()).hexdigest())

# Anonymize Time,Amount from v1 to 28
df['Time'] = hash_column(df['Time'])
df['Amount'] = hash_column(df['Amount'])
for col in df.columns:
    if col.startswith('V'):
        df[col] = hash_column(df[col])

# Check the first few rows after anonymization
df.head()

# Function to delete columns for GDPR compliance
def delete_columns(df, columns_to_delete):
    df.drop(columns=columns_to_delete, inplace=True)

# Check the DataFrame
df.head()

df['consent'] = 'Yes'  # Assuming the user has consented

# Display the DataFrame with the consent field
df.head()

# Simple GDPR compliance check
def check_gdpr_compliance(df):
    # Check if sensitive columns like 'Time' or 'Amount' are anonymized
    if 'Time' in df.columns and 'Amount' in df.columns:
        print("GDPR compliance check passed: Sensitive data anonymized.")
    else:
        print("GDPR compliance check failed: Sensitive data not anonymized.")

    # Check for the deletion of any personal columns if applicable
    # If we had deleted 'Card Number', we would verify its absence here
    if 'Card Number' not in df.columns:
        print("GDPR compliance check passed: Personal data deleted.")
    else:
        print("GDPR compliance check failed: Personal data not deleted.")

# Run the compliance check
check_gdpr_compliance(df)

# Save the consent records to a CSV file for audit purposes
df[['consent']].to_csv('user_consent_records.csv', index=False)

# Check the saved consent records
stored_consent_df = pd.read_csv('user_consent_records.csv')
stored_consent_df.head()